/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import io.github.hapjava.accessories.HomekitAccessory
import io.github.hapjava.server.impl.HomekitServer
import kotlinx.coroutines.awaitCancellation
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.runBlocking
import java.io.File
import java.net.InetAddress
import kotlin.coroutines.cancellation.CancellationException

class App(
    private val ipAddress: String,
    private val pin: String = "011-71-531"
) {

    private lateinit var server: HomekitServer
    private lateinit var dataService: DataService
    private val accessories = mutableListOf<HomekitAccessory>()
    private val channel = Channel<SensorData>()

    fun start() {
        // Initialize sensor
        val sensor = BME280Sensor(address = 0x76, bus = 1)

        // Setup storage
        val storageDir = File(System.getProperty("user.home") + "/.homekit")
        storageDir.mkdirs()

        // Create auth
        val authInfo = FileBasedHomekitAuthInfo(
            storageFile = File(storageDir, "auth.properties"),
            pin = pin
        )

        // Create server
        server = HomekitServer(InetAddress.getByName(ipAddress), 9123)

        // Create bridge
        val bridge = server.createBridge(
            authInfo,
            "Temperature, Humidity Bridge",
            1,
            "Scalangular",
            "TempBridge-v1",
            "TB-001",
            "1.0.0",
            "1.0"
        )

        // Add accessories
        dataService = DataService(sensor, channel)
        val temperature = BME280TemperatureAccessory(channel = channel)
        val humidity = BME280HumidityAccessory(channel = channel)

        bridge.addAccessory(temperature)
        bridge.addAccessory(humidity)

        accessories.addAll(listOf(temperature, humidity))

        // Start
        bridge.start()
        dataService.start()

        println("HomeKit Bridge gestartet")
        println("PIN: $pin")
        println("IP: $ipAddress:9123")

        Runtime.getRuntime().addShutdownHook(Thread { stop() })
    }

    fun stop() {
        server.stop()
        dataService.close()
        println("✓ Stopped")
    }
}

fun main() = runBlocking {
    val app = App(
        ipAddress = "192.168.2.182",
    )

    app.start()

    Runtime.getRuntime().addShutdownHook(Thread {
        app.stop()
    })

    println("Press Ctrl+C to stop")

    try {
        awaitCancellation()
    } catch (_: CancellationException) {
        println("Shutting down...")
    }
}

