/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    println("Starting")

    BME280Sensor(address = 0x76, bus = 1).use { sensor ->
        while (true) {
            try {
                val data = sensor.readSample()
                println("Timestamp: ${data.timestamp}")
                println("Temperature: ${"%.2f".format(data.temperature)}°C")
                println("Humidity: ${"%.2f".format(data.humidity)}%")
                println("Pressure: ${"%.2f".format(data.pressure)} Pa")
                println("---")
            } catch (e: InterruptedException) {
                println("Shutting down...")
            } catch (e: Exception) {
                println("Error: ${e.message}")
            }

            Thread.sleep(1000)
        }
    }
}
